name: DeathGuard
version: '1.0'
main: morritools.deathGuard.DeathGuard
api-version: '1.21'
Author: BradenM64
permissions:
  deathguard.admin:
    description: Grants access to viewing and rollback commands
  deathguard.user:
    description: Grants access to viewing commands
commands:
  deathguard:
    aliases: [ dg ]